-- Usuários do sistema e seus perfis de acesso (RF01, RF02, RNF05).
CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    -- Somente o hash da senha (ex.: BCrypt); nunca a senha em texto puro.
    senha_hash    VARCHAR(255) NOT NULL,
    perfil        VARCHAR(20)  NOT NULL,
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_usuario_perfil CHECK (perfil IN ('ADMIN', 'USER')),
    CONSTRAINT ck_usuario_email_nao_vazio CHECK (btrim(email) <> ''),
    CONSTRAINT ck_usuario_nome_nao_vazio CHECK (btrim(nome) <> '')
);

-- E-mail é o identificador de login: único sem diferenciar maiúsculas/minúsculas.
CREATE UNIQUE INDEX ux_usuario_email ON usuario (lower(email));
