-- Fornecedores e os dados cadastrais usados pelas regras de cálculo (RF03).
-- Desativação é lógica (ativo = FALSE): o fornecedor não é apagado, pois será
-- referenciado por NF-e e cotações históricas (RF14).
CREATE TABLE fornecedor (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social         VARCHAR(150) NOT NULL,
    -- Somente os 14 caracteres, sem máscara. Aceita o CNPJ numérico e o alfanumérico
    -- (12 posições alfanuméricas + 2 dígitos verificadores numéricos).
    cnpj                 VARCHAR(14)  NOT NULL,
    -- UF de emissão da NF-e do fornecedor (estado de origem, REGRAS_TRIBUTARIAS §7).
    uf                   VARCHAR(2)   NOT NULL,
    tipo                 VARCHAR(20)  NOT NULL,
    -- Opcional: fornecedor sem prazo informado é tratado como ausente (CT22).
    -- Não altera o custo efetivo (REGRAS_TRIBUTARIAS §8).
    prazo_pagamento_base VARCHAR(100),
    ativo                BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ux_fornecedor_cnpj UNIQUE (cnpj),
    CONSTRAINT ck_fornecedor_cnpj_formato CHECK (cnpj ~ '^[0-9A-Z]{12}[0-9]{2}$'),
    CONSTRAINT ck_fornecedor_uf CHECK (uf IN (
        'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA',
        'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')),
    CONSTRAINT ck_fornecedor_tipo CHECK (tipo IN ('FABRICANTE', 'ATACADISTA')),
    CONSTRAINT ck_fornecedor_razao_social_nao_vazia CHECK (btrim(razao_social) <> ''),
    CONSTRAINT ck_fornecedor_prazo_nao_vazio CHECK (prazo_pagamento_base IS NULL OR btrim(prazo_pagamento_base) <> '')
);
