-- Produtos cotados e identificados nas NF-e (RF04).
-- Desativação é lógica (ativo = FALSE): o produto não é apagado, pois será
-- referenciado por itens de NF-e e cotações históricas (RF14).
-- Nenhum dado tributário fica aqui: as regras são configuráveis (REGRAS_TRIBUTARIAS §9).
CREATE TABLE produto (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    descricao     VARCHAR(500),
    -- GTIN/EAN (tag cEAN da NF-e): identifica o mesmo produto em NF-e de fornecedores
    -- diferentes. Opcional, pois nem todo item possui ("SEM GTIN").
    gtin          VARCHAR(14),
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_produto_nome_nao_vazio CHECK (btrim(nome) <> ''),
    CONSTRAINT ck_produto_descricao_nao_vazia CHECK (descricao IS NULL OR btrim(descricao) <> ''),
    CONSTRAINT ck_produto_gtin_formato CHECK (gtin IS NULL OR gtin ~ '^([0-9]{8}|[0-9]{12,14})$')
);

-- Nome identifica o produto na cotação: único sem diferenciar maiúsculas/minúsculas.
CREATE UNIQUE INDEX ux_produto_nome ON produto (lower(nome));
CREATE UNIQUE INDEX ux_produto_gtin ON produto (gtin);
