-- NF-e importadas manualmente pelo ADMIN (RF05, RF06, RF07, RF14).
-- Guarda somente os dados originais da nota, sem aplicar regra tributária alguma:
-- créditos e custo efetivo são calculados em etapas posteriores a partir destes dados
-- e das regras configuráveis (REGRAS_TRIBUTARIAS §9).
-- A NF-e é histórica: não há alteração nem exclusão pela API.
CREATE TABLE nfe (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Chave de acesso (44 dígitos): identifica a NF-e de forma única.
    chave_acesso          VARCHAR(44)   NOT NULL,
    numero                INTEGER       NOT NULL,
    serie                 INTEGER       NOT NULL,
    data_emissao          TIMESTAMPTZ   NOT NULL,
    natureza_operacao     VARCHAR(60)   NOT NULL,
    -- Fornecedor cadastrado cujo CNPJ é o do emitente da nota.
    fornecedor_id         BIGINT        NOT NULL REFERENCES fornecedor (id),
    -- Dados do emitente como estão no XML (podem divergir do cadastro do fornecedor).
    emitente_cnpj         VARCHAR(14)   NOT NULL,
    emitente_uf           VARCHAR(2)    NOT NULL,
    -- Destinatário: opcionais, pois o destinatário pode ser identificado por CPF ou ser do exterior.
    destinatario_cnpj     VARCHAR(14),
    destinatario_uf       VARCHAR(2),
    -- Totais da nota (grupo ICMSTot), exatamente como informados no XML.
    valor_produtos        NUMERIC(15, 2) NOT NULL,
    valor_frete           NUMERIC(15, 2) NOT NULL,
    valor_seguro          NUMERIC(15, 2) NOT NULL,
    valor_desconto        NUMERIC(15, 2) NOT NULL,
    valor_outras_despesas NUMERIC(15, 2) NOT NULL,
    valor_ipi             NUMERIC(15, 2) NOT NULL,
    valor_total           NUMERIC(15, 2) NOT NULL,
    importado_em          TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT ux_nfe_chave_acesso UNIQUE (chave_acesso),
    CONSTRAINT ck_nfe_chave_acesso_formato CHECK (chave_acesso ~ '^[0-9]{44}$'),
    CONSTRAINT ck_nfe_numero CHECK (numero BETWEEN 1 AND 999999999),
    CONSTRAINT ck_nfe_serie CHECK (serie BETWEEN 0 AND 999),
    CONSTRAINT ck_nfe_natureza_operacao_nao_vazia CHECK (btrim(natureza_operacao) <> ''),
    CONSTRAINT ck_nfe_emitente_cnpj_formato CHECK (emitente_cnpj ~ '^[0-9A-Z]{12}[0-9]{2}$'),
    CONSTRAINT ck_nfe_emitente_uf CHECK (emitente_uf IN (
        'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA',
        'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')),
    CONSTRAINT ck_nfe_destinatario_cnpj_formato CHECK (
        destinatario_cnpj IS NULL OR destinatario_cnpj ~ '^[0-9A-Z]{12}[0-9]{2}$'),
    -- Além das UFs, a NF-e usa "EX" para destinatário no exterior.
    CONSTRAINT ck_nfe_destinatario_uf_formato CHECK (destinatario_uf IS NULL OR destinatario_uf ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_nfe_valores_nao_negativos CHECK (
        valor_produtos >= 0 AND valor_frete >= 0 AND valor_seguro >= 0 AND valor_desconto >= 0
        AND valor_outras_despesas >= 0 AND valor_ipi >= 0 AND valor_total >= 0)
);

CREATE INDEX ix_nfe_fornecedor ON nfe (fornecedor_id);

-- Itens (grupo det) da NF-e. Os campos tributários guardam os valores originais do XML;
-- ficam nulos quando o grupo/campo não existe na nota (ausência não é tratada como zero).
CREATE TABLE nfe_item (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nfe_id                    BIGINT         NOT NULL REFERENCES nfe (id),
    numero_item               INTEGER        NOT NULL,
    -- Produto cadastrado com o mesmo GTIN do item; nulo quando não há vínculo
    -- (item sem GTIN válido ou GTIN não cadastrado), para tratamento posterior.
    produto_id                BIGINT         REFERENCES produto (id),
    codigo_produto_fornecedor VARCHAR(60)    NOT NULL,
    -- GTIN/EAN (cEAN) somente quando válido; "SEM GTIN" ou código inválido ficam nulos.
    gtin                      VARCHAR(14),
    descricao                 VARCHAR(120)   NOT NULL,
    ncm                       VARCHAR(8)     NOT NULL,
    cfop                      VARCHAR(4)     NOT NULL,
    unidade                   VARCHAR(6)     NOT NULL,
    quantidade                NUMERIC(15, 4) NOT NULL,
    valor_unitario            NUMERIC(21, 10) NOT NULL,
    valor_produto             NUMERIC(15, 2) NOT NULL,
    -- ICMS: origem da mercadoria (0 a 8) e CST (regime normal) ou CSOSN (Simples Nacional).
    icms_origem               VARCHAR(1),
    icms_cst                  VARCHAR(2),
    icms_csosn                VARCHAR(3),
    icms_base_calculo         NUMERIC(15, 2),
    icms_aliquota             NUMERIC(7, 4),
    icms_valor                NUMERIC(15, 2),
    ipi_cst                   VARCHAR(2),
    ipi_base_calculo          NUMERIC(15, 2),
    ipi_aliquota              NUMERIC(7, 4),
    ipi_valor                 NUMERIC(15, 2),
    pis_cst                   VARCHAR(2),
    pis_base_calculo          NUMERIC(15, 2),
    pis_aliquota              NUMERIC(7, 4),
    pis_valor                 NUMERIC(15, 2),
    cofins_cst                VARCHAR(2),
    cofins_base_calculo       NUMERIC(15, 2),
    cofins_aliquota           NUMERIC(7, 4),
    cofins_valor              NUMERIC(15, 2),

    CONSTRAINT ux_nfe_item_numero UNIQUE (nfe_id, numero_item),
    CONSTRAINT ck_nfe_item_numero CHECK (numero_item BETWEEN 1 AND 990),
    CONSTRAINT ck_nfe_item_gtin_formato CHECK (gtin IS NULL OR gtin ~ '^([0-9]{8}|[0-9]{12,14})$'),
    CONSTRAINT ck_nfe_item_ncm_formato CHECK (ncm ~ '^[0-9]{2}([0-9]{6})?$'),
    CONSTRAINT ck_nfe_item_cfop_formato CHECK (cfop ~ '^[0-9]{4}$'),
    CONSTRAINT ck_nfe_item_icms_origem CHECK (icms_origem IS NULL OR icms_origem ~ '^[0-8]$'),
    CONSTRAINT ck_nfe_item_valores_nao_negativos CHECK (
        quantidade >= 0 AND valor_unitario >= 0 AND valor_produto >= 0)
);

CREATE INDEX ix_nfe_item_produto ON nfe_item (produto_id);
