-- Regras tributárias configuráveis pelo ADMIN (REGRAS_TRIBUTARIAS §9).
-- Cada linha é uma regra de crédito: "quando a operação atender às condições, o crédito do
-- tributo é obtido desta forma". Nenhuma alíquota fica no código Java: os valores são dados.
--
-- Condições nulas (ou listas vazias) significam "qualquer valor". Uma regra se aplica à
-- operação quando todas as condições preenchidas forem atendidas.
-- Quando mais de uma regra ativa se aplica ao mesmo tributo, vence a de maior prioridade;
-- empate na maior prioridade é um conflito de configuração (nenhuma regra é escolhida).
--
-- Desativação é lógica (ativa = FALSE): o cálculo registra o id e a versão da regra usada,
-- por isso a regra nunca é apagada.
CREATE TABLE regra_tributaria (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(150)  NOT NULL,
    -- Texto livre para o ADMIN: origem da regra, pendências, observações.
    observacao        VARCHAR(1000),
    -- PIS_COFINS: crédito combinado (REGRAS §4); PIS e COFINS: créditos separados (REGRAS §10).
    tributo           VARCHAR(20)   NOT NULL,
    -- PERCENTUAL_FIXO: usa a coluna aliquota;
    -- ALIQUOTA_DA_NFE: usa a alíquota do tributo destacada no item da NF-e;
    -- SEM_CREDITO: crédito zero declarado explicitamente (CT13).
    forma_aliquota    VARCHAR(20)   NOT NULL,
    -- Percentual (ex.: 7.5000 = 7,5%). Somente para PERCENTUAL_FIXO.
    aliquota          NUMERIC(7, 4),
    -- Multiplicador aplicado à alíquota obtida (ex.: 0.8 = 80% da alíquota, REGRAS §6).
    -- Obrigatório, exceto para SEM_CREDITO.
    fator             NUMERIC(5, 4),
    prioridade        INTEGER       NOT NULL DEFAULT 0,
    ativa             BOOLEAN       NOT NULL DEFAULT TRUE,

    -- Condições de aplicação (nulas = qualquer valor).
    tipo_fornecedor   VARCHAR(20),
    fornecedor_id     BIGINT        REFERENCES fornecedor (id),
    produto_id        BIGINT        REFERENCES produto (id),
    uf_origem         VARCHAR(2),
    uf_destino        VARCHAR(2),
    -- INTERNA: origem = destino; INTERESTADUAL: origem <> destino.
    abrangencia_uf    VARCHAR(20),

    -- Incrementada a cada alteração: o cálculo guarda id + versão da regra utilizada.
    versao            INTEGER       NOT NULL DEFAULT 0,
    criado_em         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    atualizado_em     TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT ck_regra_nome_nao_vazio CHECK (btrim(nome) <> ''),
    CONSTRAINT ck_regra_observacao_nao_vazia CHECK (observacao IS NULL OR btrim(observacao) <> ''),
    CONSTRAINT ck_regra_tributo CHECK (tributo IN ('ICMS', 'IPI', 'PIS', 'COFINS', 'PIS_COFINS')),
    CONSTRAINT ck_regra_forma_aliquota CHECK (forma_aliquota IN ('PERCENTUAL_FIXO', 'ALIQUOTA_DA_NFE', 'SEM_CREDITO')),
    CONSTRAINT ck_regra_aliquota_conforme_forma CHECK (
        (forma_aliquota = 'PERCENTUAL_FIXO' AND aliquota IS NOT NULL)
        OR (forma_aliquota <> 'PERCENTUAL_FIXO' AND aliquota IS NULL)),
    CONSTRAINT ck_regra_aliquota_faixa CHECK (aliquota IS NULL OR (aliquota >= 0 AND aliquota <= 100)),
    CONSTRAINT ck_regra_fator_conforme_forma CHECK (
        (forma_aliquota = 'SEM_CREDITO' AND fator IS NULL)
        OR (forma_aliquota <> 'SEM_CREDITO' AND fator IS NOT NULL)),
    CONSTRAINT ck_regra_fator_positivo CHECK (fator IS NULL OR fator > 0),
    CONSTRAINT ck_regra_tipo_fornecedor CHECK (tipo_fornecedor IS NULL OR tipo_fornecedor IN ('FABRICANTE', 'ATACADISTA')),
    CONSTRAINT ck_regra_uf_origem CHECK (uf_origem IS NULL OR uf_origem IN (
        'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA',
        'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')),
    CONSTRAINT ck_regra_uf_destino CHECK (uf_destino IS NULL OR uf_destino IN (
        'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA',
        'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')),
    CONSTRAINT ck_regra_abrangencia_uf CHECK (abrangencia_uf IS NULL OR abrangencia_uf IN ('INTERNA', 'INTERESTADUAL')),
    -- Combinações contraditórias nunca se aplicariam a operação alguma.
    CONSTRAINT ck_regra_abrangencia_coerente CHECK (
        abrangencia_uf IS NULL OR uf_origem IS NULL OR uf_destino IS NULL
        OR (abrangencia_uf = 'INTERNA' AND uf_origem = uf_destino)
        OR (abrangencia_uf = 'INTERESTADUAL' AND uf_origem <> uf_destino))
);

-- Nome identifica a regra para o ADMIN: único sem diferenciar maiúsculas/minúsculas.
CREATE UNIQUE INDEX ux_regra_tributaria_nome ON regra_tributaria (lower(nome));
CREATE INDEX ix_regra_tributaria_ativa ON regra_tributaria (ativa, tributo);

-- Condição: códigos de origem da mercadoria (tag orig do ICMS na NF-e, 0 a 8).
-- Sem linhas = qualquer origem. Quais códigos caracterizam "importado" é configuração do ADMIN.
CREATE TABLE regra_tributaria_origem (
    regra_id BIGINT     NOT NULL REFERENCES regra_tributaria (id) ON DELETE CASCADE,
    origem   VARCHAR(1) NOT NULL,

    CONSTRAINT pk_regra_tributaria_origem PRIMARY KEY (regra_id, origem),
    CONSTRAINT ck_regra_tributaria_origem CHECK (origem ~ '^[0-8]$')
);

-- Condição: CFOPs da operação. Sem linhas = qualquer CFOP.
CREATE TABLE regra_tributaria_cfop (
    regra_id BIGINT     NOT NULL REFERENCES regra_tributaria (id) ON DELETE CASCADE,
    cfop     VARCHAR(4) NOT NULL,

    CONSTRAINT pk_regra_tributaria_cfop PRIMARY KEY (regra_id, cfop),
    CONSTRAINT ck_regra_tributaria_cfop CHECK (cfop ~ '^[0-9]{4}$')
);

-- Parâmetros gerais do cálculo, alteráveis pelo ADMIN. As chaves são fixas (conhecidas pelo
-- código); os valores são dados. Valor nulo = ainda não definido.
CREATE TABLE parametro_calculo (
    chave         VARCHAR(40)   PRIMARY KEY,
    valor         VARCHAR(500),
    versao        INTEGER       NOT NULL DEFAULT 0,
    atualizado_em TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT ck_parametro_valor_nao_vazio CHECK (valor IS NULL OR btrim(valor) <> '')
);
