-- Etapa 8: cálculo do custo efetivo (REGRAS_TRIBUTARIAS §4, §5 e §10).

-- 1. Componentes de valor do item da NF-e (grupo prod: vFrete, vSeg, vDesc, vOutro).
-- Ficam nulos quando a tag não existe no item, como os demais campos opcionais do XML;
-- itens importados antes desta migration também ficam nulos (não foram lidos).
ALTER TABLE nfe_item
    ADD COLUMN valor_frete           NUMERIC(15, 2),
    ADD COLUMN valor_seguro          NUMERIC(15, 2),
    ADD COLUMN valor_desconto        NUMERIC(15, 2),
    ADD COLUMN valor_outras_despesas NUMERIC(15, 2),
    ADD CONSTRAINT ck_nfe_item_componentes_nao_negativos CHECK (
        (valor_frete IS NULL OR valor_frete >= 0) AND (valor_seguro IS NULL OR valor_seguro >= 0)
        AND (valor_desconto IS NULL OR valor_desconto >= 0)
        AND (valor_outras_despesas IS NULL OR valor_outras_despesas >= 0));

-- 2. Parâmetros do cálculo. Nulo = ainda não definido:
-- o cálculo informa a pendência em vez de escolher uma opção.
INSERT INTO parametro_calculo (chave, valor)
VALUES
    -- De onde vêm os valores (preço) da operação: item da NF-e ou valores informados.
    ('FONTE_VALORES_OPERACAO', NULL),
    -- De onde vêm origem, CFOP, UF de origem e alíquotas destacadas.
    ('FONTE_DADOS_FISCAIS', NULL),
    -- Componentes somados no "valor da operação" (DESCONTO é subtraído).
    ('COMPOSICAO_VALOR_OPERACAO', NULL),
    -- REGRAS_TRIBUTARIAS §4: cada crédito é calculado sobre o valor da operação.
    ('COMPOSICAO_BASE_CREDITOS', 'VALOR_OPERACAO'),
    -- Critério de arredondamento a 2 casas (meio para cima ou meio para o par).
    ('CRITERIO_ARREDONDAMENTO', NULL);

-- 3. Resultado de cada cálculo executado. Guarda uma cópia (snapshot) de tudo o que foi
-- usado: operação, parâmetros, valores, alíquotas e regras (id, versão e valores), para
-- explicar o resultado mesmo depois que regras ou parâmetros forem alterados.
CREATE TABLE calculo_custo (
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- CALCULADO: custo efetivo obtido; INCOMPLETO: há pendência bloqueante (custo nulo).
    status                            VARCHAR(20)    NOT NULL,
    executado_em                      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    executado_por_id                  BIGINT         NOT NULL REFERENCES usuario (id),

    -- Operação: item de NF-e de referência (opcional) e partes envolvidas.
    nfe_item_id                       BIGINT         REFERENCES nfe_item (id),
    -- Item de NF-e de onde vieram os dados fiscais (pode diferir com ULTIMA_NFE_FORNECEDOR_PRODUTO).
    nfe_item_dados_fiscais_id         BIGINT         REFERENCES nfe_item (id),
    fornecedor_id                     BIGINT         NOT NULL REFERENCES fornecedor (id),
    produto_id                        BIGINT         REFERENCES produto (id),
    tipo_fornecedor                   VARCHAR(20)    NOT NULL,
    uf_origem                         VARCHAR(2),
    uf_destino                        VARCHAR(2),
    origem_mercadoria                 VARCHAR(1),
    cfop                              VARCHAR(4),
    quantidade                        NUMERIC(15, 4),

    -- Parâmetros vigentes no momento do cálculo (nulos = não definidos naquele momento).
    param_fonte_valores               VARCHAR(40),
    param_fonte_dados_fiscais         VARCHAR(40),
    param_fonte_uf_origem             VARCHAR(40),
    param_composicao_valor_operacao   VARCHAR(200),
    param_composicao_base_creditos    VARCHAR(200),
    param_arredondamento              VARCHAR(40),
    param_criterio_arredondamento     VARCHAR(40),

    -- Componentes de valor usados (nulos = não disponíveis na fonte).
    valor_produto                     NUMERIC(15, 2),
    valor_ipi                         NUMERIC(15, 2),
    valor_frete                       NUMERIC(15, 2),
    valor_seguro                      NUMERIC(15, 2),
    valor_outras_despesas             NUMERIC(15, 2),
    valor_desconto                    NUMERIC(15, 2),

    -- Alíquotas destacadas nos dados fiscais da operação (usadas por ALIQUOTA_DA_NFE).
    aliquota_icms_operacao            NUMERIC(7, 4),
    aliquota_ipi_operacao             NUMERIC(7, 4),
    aliquota_pis_operacao             NUMERIC(7, 4),
    aliquota_cofins_operacao          NUMERIC(7, 4),

    -- Resultado. Valores nulos quando não puderam ser obtidos.
    valor_operacao                    NUMERIC(15, 2),
    base_creditos                     NUMERIC(15, 2),
    total_creditos_sem_arredondamento NUMERIC(27, 12),
    total_creditos                    NUMERIC(15, 2),
    -- total_creditos - total_creditos_sem_arredondamento: a diferença nunca é escondida.
    diferenca_arredondamento          NUMERIC(27, 12),
    custo_efetivo                     NUMERIC(15, 2),

    CONSTRAINT ck_calculo_status CHECK (status IN ('CALCULADO', 'INCOMPLETO')),
    CONSTRAINT ck_calculo_custo_somente_calculado CHECK (
        (status = 'CALCULADO' AND custo_efetivo IS NOT NULL AND total_creditos IS NOT NULL)
        OR (status = 'INCOMPLETO' AND custo_efetivo IS NULL)),
    CONSTRAINT ck_calculo_tipo_fornecedor CHECK (tipo_fornecedor IN ('FABRICANTE', 'ATACADISTA')),
    CONSTRAINT ck_calculo_origem CHECK (origem_mercadoria IS NULL OR origem_mercadoria ~ '^[0-8]$'),
    CONSTRAINT ck_calculo_cfop CHECK (cfop IS NULL OR cfop ~ '^[0-9]{4}$')
);

CREATE INDEX ix_calculo_custo_fornecedor ON calculo_custo (fornecedor_id);
CREATE INDEX ix_calculo_custo_produto ON calculo_custo (produto_id);
CREATE INDEX ix_calculo_custo_nfe_item ON calculo_custo (nfe_item_id);

-- Crédito de cada tributo, com a cópia da regra utilizada no momento do cálculo.
CREATE TABLE calculo_custo_credito (
    calculo_id                BIGINT         NOT NULL REFERENCES calculo_custo (id) ON DELETE CASCADE,
    posicao                   INTEGER        NOT NULL,
    -- ICMS, IPI, PIS, COFINS ou PIS_COFINS (regra combinada aplicada uma única vez).
    tributo                   VARCHAR(20)    NOT NULL,
    situacao                  VARCHAR(30)    NOT NULL,
    -- Regra usada (ou a primeira em conflito) e sua versão no momento do cálculo.
    regra_id                  BIGINT         REFERENCES regra_tributaria (id),
    regra_versao              INTEGER,
    regra_nome                VARCHAR(150),
    forma_aliquota            VARCHAR(20),
    -- Alíquota obtida (fixa da regra ou da operação), fator e alíquota aplicada = obtida × fator.
    aliquota_obtida           NUMERIC(7, 4),
    fator                     NUMERIC(5, 4),
    aliquota_aplicada         NUMERIC(12, 8),
    base_calculo              NUMERIC(15, 2),
    valor_sem_arredondamento  NUMERIC(27, 12),
    -- Preenchido quando o arredondamento é por crédito (ou não foi necessário).
    valor                     NUMERIC(15, 2),
    -- Em conflito: todas as regras empatadas (id:versão), para análise do ADMIN.
    regras_em_conflito        VARCHAR(500),
    mensagem                  VARCHAR(500),

    CONSTRAINT pk_calculo_custo_credito PRIMARY KEY (calculo_id, posicao),
    CONSTRAINT ck_calculo_credito_tributo CHECK (tributo IN ('ICMS', 'IPI', 'PIS', 'COFINS', 'PIS_COFINS')),
    CONSTRAINT ck_calculo_credito_situacao CHECK (situacao IN (
        'CALCULADO', 'SEM_CREDITO', 'REGRA_AUSENTE', 'CONFLITO_REGRAS',
        'ALIQUOTA_INDISPONIVEL', 'CONFIGURACAO_INCONSISTENTE', 'NAO_CALCULADO'))
);

-- Pendências (bloqueiam o custo efetivo) e avisos (informativos) de cada cálculo.
CREATE TABLE calculo_custo_pendencia (
    calculo_id  BIGINT       NOT NULL REFERENCES calculo_custo (id) ON DELETE CASCADE,
    posicao     INTEGER      NOT NULL,
    tipo        VARCHAR(40)  NOT NULL,
    bloqueante  BOOLEAN      NOT NULL,
    mensagem    VARCHAR(500) NOT NULL,

    CONSTRAINT pk_calculo_custo_pendencia PRIMARY KEY (calculo_id, posicao)
);
