-- Etapa 9: cotação e comparação de fornecedores (RF08, RF10, RF11, RF12).
--
-- Cotação: necessidade de compra de um produto (quantidade e condições) e as opções de
-- fornecedores informadas. Comparação: execução que calcula todas as opções com a mesma
-- configuração e as ordena pelo custo efetivo. Uma cotação pode ser comparada várias vezes;
-- cada comparação é um registro histórico imutável (nada é sobrescrito).

CREATE TABLE cotacao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id      BIGINT         NOT NULL REFERENCES produto (id),
    -- Quantidade da necessidade de compra: todas as opções são comparadas para essa quantidade.
    quantidade      NUMERIC(15, 4) NOT NULL,
    -- Texto livre: condições e observações da cotação.
    descricao       VARCHAR(500),
    criado_em       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    criado_por_id   BIGINT         NOT NULL REFERENCES usuario (id),

    CONSTRAINT ck_cotacao_quantidade_positiva CHECK (quantidade > 0),
    CONSTRAINT ck_cotacao_descricao_nao_vazia CHECK (descricao IS NULL OR btrim(descricao) <> '')
);

CREATE INDEX ix_cotacao_produto ON cotacao (produto_id);

-- Opção de fornecedor da cotação. Os valores e dados fiscais informados só são usados no
-- cálculo quando FONTE_VALORES_OPERACAO / FONTE_DADOS_FISCAIS = INFORMADO; o item de NF-e,
-- quando FONTE_* = NFE_ITEM. Nulo = não informado (nunca é tratado como zero).
CREATE TABLE cotacao_opcao (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotacao_id             BIGINT         NOT NULL REFERENCES cotacao (id),
    fornecedor_id          BIGINT         NOT NULL REFERENCES fornecedor (id),
    nfe_item_id            BIGINT         REFERENCES nfe_item (id),
    -- Condição de pagamento desta opção (texto livre). Exibida; não altera o custo (REGRAS §8).
    condicao_pagamento     VARCHAR(100),
    observacao             VARCHAR(500),

    valor_produto          NUMERIC(15, 2),
    valor_ipi              NUMERIC(15, 2),
    valor_frete            NUMERIC(15, 2),
    valor_seguro           NUMERIC(15, 2),
    valor_outras_despesas  NUMERIC(15, 2),
    valor_desconto         NUMERIC(15, 2),

    origem_mercadoria      VARCHAR(1),
    cfop                   VARCHAR(4),
    aliquota_icms          NUMERIC(7, 4),
    aliquota_ipi           NUMERIC(7, 4),
    aliquota_pis           NUMERIC(7, 4),
    aliquota_cofins        NUMERIC(7, 4),

    criado_em              TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT ck_opcao_condicao_nao_vazia CHECK (condicao_pagamento IS NULL OR btrim(condicao_pagamento) <> ''),
    CONSTRAINT ck_opcao_observacao_nao_vazia CHECK (observacao IS NULL OR btrim(observacao) <> ''),
    CONSTRAINT ck_opcao_valores_nao_negativos CHECK (
        (valor_produto IS NULL OR valor_produto >= 0) AND (valor_ipi IS NULL OR valor_ipi >= 0)
        AND (valor_frete IS NULL OR valor_frete >= 0) AND (valor_seguro IS NULL OR valor_seguro >= 0)
        AND (valor_outras_despesas IS NULL OR valor_outras_despesas >= 0)
        AND (valor_desconto IS NULL OR valor_desconto >= 0)),
    CONSTRAINT ck_opcao_origem CHECK (origem_mercadoria IS NULL OR origem_mercadoria ~ '^[0-8]$'),
    CONSTRAINT ck_opcao_cfop CHECK (cfop IS NULL OR cfop ~ '^[0-9]{4}$'),
    CONSTRAINT ck_opcao_aliquotas_faixa CHECK (
        (aliquota_icms IS NULL OR aliquota_icms BETWEEN 0 AND 100)
        AND (aliquota_ipi IS NULL OR aliquota_ipi BETWEEN 0 AND 100)
        AND (aliquota_pis IS NULL OR aliquota_pis BETWEEN 0 AND 100)
        AND (aliquota_cofins IS NULL OR aliquota_cofins BETWEEN 0 AND 100))
);

CREATE INDEX ix_cotacao_opcao_cotacao ON cotacao_opcao (cotacao_id);

-- Execução da comparação de uma cotação.
CREATE TABLE comparacao (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotacao_id           BIGINT         NOT NULL REFERENCES cotacao (id),
    executado_em         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    executado_por_id     BIGINT         NOT NULL REFERENCES usuario (id),
    -- Cópia do produto e da quantidade no momento da comparação.
    produto_id           BIGINT         NOT NULL REFERENCES produto (id),
    produto_nome         VARCHAR(150)   NOT NULL,
    quantidade           NUMERIC(15, 4) NOT NULL,
    total_opcoes         INTEGER        NOT NULL,
    total_classificadas  INTEGER        NOT NULL,

    CONSTRAINT ck_comparacao_totais CHECK (total_classificadas >= 0 AND total_classificadas <= total_opcoes)
);

CREATE INDEX ix_comparacao_cotacao ON comparacao (cotacao_id);

-- Configuração usada em TODAS as opções da comparação: cópia de cada parâmetro
-- (valor nulo = não definido naquele momento).
CREATE TABLE comparacao_parametro (
    comparacao_id  BIGINT       NOT NULL REFERENCES comparacao (id) ON DELETE CASCADE,
    posicao        INTEGER      NOT NULL,
    chave          VARCHAR(40)  NOT NULL,
    valor          VARCHAR(500),

    CONSTRAINT pk_comparacao_parametro PRIMARY KEY (comparacao_id, posicao),
    CONSTRAINT ux_comparacao_parametro_chave UNIQUE (comparacao_id, chave)
);

-- Regras ativas no momento da comparação (id e versão), usadas por todas as opções.
CREATE TABLE comparacao_regra (
    comparacao_id  BIGINT       NOT NULL REFERENCES comparacao (id) ON DELETE CASCADE,
    posicao        INTEGER      NOT NULL,
    regra_id       BIGINT       NOT NULL REFERENCES regra_tributaria (id),
    regra_versao   INTEGER      NOT NULL,
    regra_nome     VARCHAR(150) NOT NULL,
    tributo        VARCHAR(20)  NOT NULL,
    prioridade     INTEGER      NOT NULL,

    CONSTRAINT pk_comparacao_regra PRIMARY KEY (comparacao_id, posicao)
);

-- Resultado de cada opção na comparação, na ordem de apresentação: primeiro as classificadas
-- (posição 1..n), depois as que não puderam ser classificadas, com o motivo.
CREATE TABLE comparacao_resultado (
    comparacao_id            BIGINT         NOT NULL REFERENCES comparacao (id) ON DELETE CASCADE,
    ordem                    INTEGER        NOT NULL,
    opcao_id                 BIGINT         NOT NULL REFERENCES cotacao_opcao (id),
    -- Cálculo executado para a opção (nulo quando a opção não pôde ser calculada).
    calculo_id               BIGINT         REFERENCES calculo_custo (id),
    situacao                 VARCHAR(40)    NOT NULL,
    -- Posição no ranking; somente para CLASSIFICADA.
    posicao                  INTEGER,
    -- Mesmo custo efetivo de outra opção classificada (desempate pela ordem de cadastro da opção).
    empate                   BOOLEAN        NOT NULL DEFAULT FALSE,
    motivo                   VARCHAR(2000),

    -- Cópia dos dados apresentados, no momento da comparação.
    fornecedor_id            BIGINT         NOT NULL REFERENCES fornecedor (id),
    fornecedor_razao_social  VARCHAR(150)   NOT NULL,
    tipo_fornecedor          VARCHAR(20)    NOT NULL,
    fornecedor_ativo         BOOLEAN        NOT NULL,
    produto_ativo            BOOLEAN        NOT NULL,
    condicao_pagamento       VARCHAR(100),
    prazo_pagamento_base     VARCHAR(100),
    status_calculo           VARCHAR(20),
    quantidade               NUMERIC(15, 4),
    valor_operacao           NUMERIC(15, 2),
    total_creditos           NUMERIC(15, 2),
    custo_efetivo            NUMERIC(15, 2),

    CONSTRAINT pk_comparacao_resultado PRIMARY KEY (comparacao_id, ordem),
    CONSTRAINT ux_comparacao_resultado_opcao UNIQUE (comparacao_id, opcao_id),
    CONSTRAINT ck_comparacao_resultado_situacao CHECK (situacao IN (
        'CLASSIFICADA', 'CALCULO_INCOMPLETO', 'FORNECEDOR_DESATIVADO', 'PRODUTO_DESATIVADO',
        'CFOP_NAO_PARTICIPANTE', 'CFOPS_PARTICIPANTES_NAO_DEFINIDOS', 'QUANTIDADE_DIVERGENTE')),
    -- Opção classificada tem posição, cálculo CALCULADO e custo efetivo; as demais não têm posição
    -- (INCOMPLETO nunca é tratado como custo zero).
    CONSTRAINT ck_comparacao_resultado_classificada CHECK (
        (situacao = 'CLASSIFICADA' AND posicao IS NOT NULL AND posicao > 0 AND calculo_id IS NOT NULL
            AND status_calculo = 'CALCULADO' AND custo_efetivo IS NOT NULL)
        OR (situacao <> 'CLASSIFICADA' AND posicao IS NULL AND empate = FALSE)),
    CONSTRAINT ck_comparacao_resultado_status CHECK (status_calculo IS NULL OR status_calculo IN ('CALCULADO', 'INCOMPLETO')),
    CONSTRAINT ck_comparacao_resultado_tipo CHECK (tipo_fornecedor IN ('FABRICANTE', 'ATACADISTA'))
);

CREATE UNIQUE INDEX ux_comparacao_resultado_posicao ON comparacao_resultado (comparacao_id, posicao)
    WHERE posicao IS NOT NULL;
CREATE INDEX ix_comparacao_resultado_calculo ON comparacao_resultado (calculo_id);
